version: '3.3'

services:
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    container_name: jeteo-backup
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET_NAME=backupy-newbies
      - AWS_S3_PATH=jeteo
      - BACKUP_RETENTION_DAYS=14
      - BACKUP_STOP_CONTAINER_LABEL=jeteo
    volumes:
      - jeteo-db-data:/backup/db:ro
      - jeteo-api-storage:/backup/api-storage:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  jeteo-db:
    image: postgres:15.3
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=jeteo
    environment:
      POSTGRES_USER: jeteo
      POSTGRES_PASSWORD: jeteo
    ports:
      - "5432:5432"
    volumes:
      - jeteo-db-data:/var/lib/postgresql/data
  jeteo-web:
    image: ghcr.io/newbies-workplace/jeteo-web:latest
    restart: unless-stopped
    container_name: jeteo-web
    ports:
      - "3000:3000"
    networks:
      - reverse-proxy_global
  jeteo-api:
    image: ghcr.io/newbies-workplace/jeteo-api:latest
    restart: unless-stopped
    container_name: jeteo-api
    labels:
      - docker-volume-backup.stop-during-backup=jeteo
    volumes:
      - jeteo-api-storage:/jeteo-api-storage
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - GOOGLE_CALLBACK_URL
      - JWT_SECRET
      - CLIENT_URL
      - DATABASE_URL
      - NEXT_PUBLIC_BACKEND_URL
    ports:
      - "3001:3001"
    depends_on:
      - jeteo-db

networks:
  reverse-proxy_global:
    external: true

volumes:
  jeteo-db-data:
  jeteo-api-storage:
