version: '3.4'

name: "jeteo-monorepo"

services:
  jeteo-db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: jeteo
      POSTGRES_PASSWORD: jeteo
    ports:
      - "5432:5432"
    volumes:
      - jeteo-db-data:/var/lib/postgresql/data
  jeteo-web:
    build:
      context: ../
      target: jeteo-web
    restart: unless-stopped
    container_name: jeteo-web
    env_file:
      - ../.env.docker
    ports:
      - "3000:3000"
  jeteo-api:
    build:
      context: ../
      target: jeteo-api
    restart: unless-stopped
    container_name: jeteo-api
    volumes:
      - jeteo-api-storage:/jeteo-api-storage
    env_file:
      - ../.env.docker
    ports:
      - "3001:3001"
    depends_on:
      - jeteo-db

volumes:
  jeteo-db-data:
  jeteo-api-storage:
