version: '3.4'

name: jeteo

services:
  jeteo-db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: jeteo
      POSTGRES_PASSWORD: jeteo
    ports:
      - "5432:5432"
    volumes:
      - jeteo-db-data:/var/lib/postgresql/data
  jeteo-app:
    build:
      context: ../
    restart: unless-stopped
    container_name: jeteo-app
    env_file:
      - ../.env.docker
    ports:
      - "3000:3000"

volumes:
  jeteo-db-data:
  jeteo-api-storage:
