version: '3.3'

services:
  jeteo-db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: jeteo
      POSTGRES_PASSWORD: jeteo
    ports:
      - "5432:5432"
    volumes:
      - jeteo-db-data:/var/lib/postgresql/data
  jeteo-web:
    image: ghcr.io/newbies-workplace/jeteo-web:latest
    restart: unless-stopped
    container_name: jeteo-web
    ports:
      - "3000:3000"
    networks:
      - reverse-proxy_global
  jeteo-api:
    image: ghcr.io/newbies-workplace/jeteo-api:latest
    restart: unless-stopped
    container_name: jeteo-api
    volumes:
      - jeteo-api-storage:/storage
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - GOOGLE_CALLBACK_URL
      - JWT_SECRET
      - CLIENT_URL
      - DATABASE_URL
    ports:
      - "3001:3001"
    depends_on:
      - jeteo-db

networks:
  reverse-proxy_global:
    external: true

volumes:
  jeteo-db-data:
  jeteo-api-storage: