version: '3.3'

services:
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    container_name: jeteo-backup
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_S3_BUCKET_NAME=backupy-newbies
      - AWS_S3_PATH=jeteo
      - BACKUP_RETENTION_DAYS=14
      - BACKUP_STOP_CONTAINER_LABEL=jeteo
    volumes:
      - jeteo-db-data:/backup/db:ro
      - jeteo-api-storage:/backup/api-storage:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  jeteo-db:
    image: postgres:15.3
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=jeteo
    environment:
      POSTGRES_USER: jeteo
      POSTGRES_PASSWORD: jeteo
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - jeteo-db-data:/var/lib/postgresql/data
  jeteo-app:
    image: ghcr.io/newbies-workplace/jeteo-app:latest
    restart: unless-stopped
    container_name: jeteo-app
    labels:
      - docker-volume-backup.stop-during-backup=jeteo
    volumes:
      - jeteo-api-storage:/jeteo-api-storage
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - reverse-proxy_global
    depends_on:
      - jeteo-db

networks:
  reverse-proxy_global:
    external: true

volumes:
  jeteo-db-data:
  jeteo-api-storage:
